on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-frontend:
    environment: github-pages
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: install packages
        run: npm install

      - name: create build
        env:
          REACT_APP_BLOCKFROST_API_KEY: ${{ secrets.REACT_APP_BLOCKFROST_API_KEY }}
        run: |
          echo "API_KEY=$REACT_APP_BLOCKFROST_API_KEY"
          npm run build

      - name: Fix permissions
        run: |
          chmod -c -R +rX "build/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: 'github-pages'
          path: build/

      - name: deploy to github pages
        uses: actions/deploy-pages@v4
